name: Testing
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Echo Info
        run: echo "${{ github.event.action }}"
      - name: Write a comment
        uses: actions/github@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "commit SHA: ${{ github.event.pull_request.head.sha }}"
